/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectCodeRouteImport } from './routes/projects.$projectCode'
import { Route as TasksMyRouteImport } from './routes/tasks.my'
import { Route as ProjectsProjectCodeGroupsGroupCodeRouteImport } from './routes/projects.$projectCode_.groups.$groupCode'
import { Route as ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRouteImport } from './routes/projects.$projectCode_.groups.$groupCode_.tasks.$taskNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectCodeRoute = ProjectsProjectCodeRouteImport.update({
  id: '/projects/$projectCode',
  path: '/projects/$projectCode',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksMyRoute = TasksMyRouteImport.update({
  id: '/tasks/my',
  path: '/tasks/my',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectCodeGroupsGroupCodeRoute =
  ProjectsProjectCodeGroupsGroupCodeRouteImport.update({
    id: '/projects/$projectCode_/groups/$groupCode',
    path: '/projects/$projectCode/groups/$groupCode',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRoute =
  ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRouteImport.update({
    id: '/projects/$projectCode_/groups/$groupCode_/tasks/$taskNumber',
    path: '/projects/$projectCode/groups/$groupCode/tasks/$taskNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectCode': typeof ProjectsProjectCodeRoute
  '/tasks/my': typeof TasksMyRoute
  '/projects/$projectCode/groups/$groupCode': typeof ProjectsProjectCodeGroupsGroupCodeRoute
  '/projects/$projectCode/groups/$groupCode/tasks/$taskNumber': typeof ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectCode': typeof ProjectsProjectCodeRoute
  '/tasks/my': typeof TasksMyRoute
  '/projects/$projectCode/groups/$groupCode': typeof ProjectsProjectCodeGroupsGroupCodeRoute
  '/projects/$projectCode/groups/$groupCode/tasks/$taskNumber': typeof ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectCode': typeof ProjectsProjectCodeRoute
  '/tasks/my': typeof TasksMyRoute
  '/projects/$projectCode_/groups/$groupCode': typeof ProjectsProjectCodeGroupsGroupCodeRoute
  '/projects/$projectCode_/groups/$groupCode_/tasks/$taskNumber': typeof ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$projectCode'
    | '/tasks/my'
    | '/projects/$projectCode/groups/$groupCode'
    | '/projects/$projectCode/groups/$groupCode/tasks/$taskNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$projectCode'
    | '/tasks/my'
    | '/projects/$projectCode/groups/$groupCode'
    | '/projects/$projectCode/groups/$groupCode/tasks/$taskNumber'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectCode'
    | '/tasks/my'
    | '/projects/$projectCode_/groups/$groupCode'
    | '/projects/$projectCode_/groups/$groupCode_/tasks/$taskNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectCodeRoute: typeof ProjectsProjectCodeRoute
  TasksMyRoute: typeof TasksMyRoute
  ProjectsProjectCodeGroupsGroupCodeRoute: typeof ProjectsProjectCodeGroupsGroupCodeRoute
  ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRoute: typeof ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectCode': {
      id: '/projects/$projectCode'
      path: '/projects/$projectCode'
      fullPath: '/projects/$projectCode'
      preLoaderRoute: typeof ProjectsProjectCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/my': {
      id: '/tasks/my'
      path: '/tasks/my'
      fullPath: '/tasks/my'
      preLoaderRoute: typeof TasksMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectCode_/groups/$groupCode': {
      id: '/projects/$projectCode_/groups/$groupCode'
      path: '/projects/$projectCode/groups/$groupCode'
      fullPath: '/projects/$projectCode/groups/$groupCode'
      preLoaderRoute: typeof ProjectsProjectCodeGroupsGroupCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectCode_/groups/$groupCode_/tasks/$taskNumber': {
      id: '/projects/$projectCode_/groups/$groupCode_/tasks/$taskNumber'
      path: '/projects/$projectCode/groups/$groupCode/tasks/$taskNumber'
      fullPath: '/projects/$projectCode/groups/$groupCode/tasks/$taskNumber'
      preLoaderRoute: typeof ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectCodeRoute: ProjectsProjectCodeRoute,
  TasksMyRoute: TasksMyRoute,
  ProjectsProjectCodeGroupsGroupCodeRoute:
    ProjectsProjectCodeGroupsGroupCodeRoute,
  ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRoute:
    ProjectsProjectCodeGroupsGroupCodeTasksTaskNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
